language: python
cache:
  - pip
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
script:
  - bash install_travis.sh
  - python setup.py install
  - python testing/t.py
deploy:
  provider: pypi
  user: tisaconundrum
  password:
    secure: WKib7Bz+0w0RIXjpG1H5tJSLXDEf/EFDJFFdLcK0ExlHN908hUgqcvJiJDdRhZwSkCSodjAER1gJDWrtgiu+nwSyM1lBczfA+wkwk5koQsNscE+wP9swVStSdl4yNMU6JgBTPoav+SR5nBStbF6X3UDi6K+qMFPjzeCNn+6Vd08YaEK9zrkp8Yt5D3WekIwZcKSwvo5Tn9v9GceupNeszvmRaYgAVEPtbEKbZ/fkjYIz0O77Fti4twyvEzHFtc1H1a8jIYfefYLPUwse6rwjJJVDOgE5O/+LGHUXnQFNNrh5tZRGYTKkek3bf/z8ASNGSlgUFpfwWWsaooXGYzZOWJDLbyi450HVNd9lSduXPc3Fs3GyQ5zk9Wc0kzLzHLqh1HtyPA/qInlEsctw7Z7aHVnnua3VTaeqBX8/MAPfEOsvmb2nHJCBwNd7LoBNHg44KKm11ICHSVsPVMc4AG7tTt+jV6H9edT0m/yVxxmk9zNEpAgSf7FXOrvNHtTMD0iEhKPtU+jQ2zMROYyNgnqvVoAnfPUtsDEYM3zWT2faN2xQpWmSYz6puhN8CymTlKx9VgbSe5jjwHLYrIEV0RFs1+j5X9JEDOyMOky5bYltZ/zgZsa3x0bn1OhTALX2HRxoZbMeAXCbX2tcKqbROqJ4Lu9VVXS6yL7s6sZDtUhU2zE=
  distributions: sdist bdist_wheel
  on:
    branch: dev
after_deploy:
  - conda env create -n ppsg -f environment.yml
  - source activate ppsg
  - point_spectra_gui
